name: Release website
on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
      - name: copy builds to server
        run: |
          rsync -vrm   ./* ${{ secrets.USER_IP }}:/var/www/code-pro/
          ssh ${{ secrets.USER_IP }} "cd /var/www/code-pro/ && pnpm install && cd /var/www/code-pro/client && pnpm build && cd /var/www/code-pro/server && pnpm run kill && pnpm run deploy"